import smtplib
import random 
from email.message import EmailMessage


def sendMail(to,state = False):

    otp = ""

    #login credentials
    sender = 'playgroundbookingsystem@gmail.com'
    password = 'qwerty@456'

    msg = EmailMessage()
    msg['From'] = sender
    msg['To'] = to

    if state:
        msg['Subject'] = 'Mail Subject '
        msg.set_content('mail content in plain text')
        msg.add_alternative("""\
            <html>
                <body>
                    <h1>Congratulation You have successfully booked the playground</h1>
                </body>
            </html>
            """, subtype='html')
    else:
        #otp generation
        for i in range(6):
            otp += str(random.randint(0,9))
        print(otp)

        #otp mail text
        msg['Subject'] = 'Otp for signup in OnlinePlaygroundBookingSystem'
        txt = f'Your otp for the email validation is : {otp} . Please enter this credentials to complete your signup' 
        msg.set_content(txt)
        txt = '''
            <html>
            <body style = 'font-size:16px;'>
                Please do not share this OTP with anyone. <br>
                Your OTP is : <span style = 'font-size :24px; color:red;'> ''' + otp + '''</span><br>
                Please enter the credentials within 15 minutes to complete your Sign up
                This is an autogenerated mail. So please do not reply.
            </body>
            </html>'''
        msg.add_alternative(txt, subtype='html')
        # return otp

    # print(msg)
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        #login
        smtp.login(sender, password)
        #send message
        smtp.send_message(msg)

    #for returning the otp to the signup page for verification
    if not state:
        return otp

# print(sendMail('rittikghosh12rg@gmail.com',True))
